### ISSUE TITLE
No way to pass extra options to vsce

### ISSUE THREAD

**Issue by zobo** [felipecrs/semantic-release-vsce#115]
Due to `master`->`main` branch rename we need to pass `--githubBranch` option to `vsce`. I currently see no way of doing that and because of that relative image paths on VSCode Market place are broken.

**Comment by felipecrs** [comment]
This is fixed in `vsce` 1.86.0 or higher, you don't need to pass `--githubBranch` anymore, it automatically uses the default.

**Comment by felipecrs** [comment]
I see that you have `"vsce": "^1.85.0",` in your `package.json`. You can remove it as semantic-release-vsce also includes it.

**Comment by felipecrs** [comment]
Nonetheless, what this issue says is true. However, the best way to fix it would be through https://github.com/microsoft/vscode-vsce/issues/548.

**Comment by zobo** [comment]
Thank you so much for pointing this out. I also agree about your proposed change to `vsce`. This is the reason why I didn't notice that change from `master` to `HEAD` as I was so determined to find a different way to pass configuration data to `vsce` via ENV or other means.

**Comment by jedwards1211** [comment]
I need a way to pass `--insiders` to `vsce`

**Comment by felipecrs** [comment]
Right, I'm okay with new options for this plugin like:

```json
{
  "packageOpts": ["--whatever", "you-want"],
  "publishOpts": ["--whatever", "you-want"],
  "ovsxPublishOpts": ["--whatever", "you-want"]
}
```

**Comment by jedwards1211** [comment]
cool, I'll try to make a PR soon, I think `vscePublishOpts` would be the least ambiguous

**Comment by felipecrs** [comment]
> I think vscePublishOpts would be the least ambiguous

Yep, agreed.
