### ISSUE TITLE
Bug semantic-release v12 does break your plugin 

### ISSUE THREAD

**Issue by buehler** [felipecrs/semantic-release-vsce#13]
Hi There

First of all: Cool!

I just want to check if I do something wrong:

```bash
[Semantic release]: An error occurred while running semantic-release: Error: The "getLastRelease" plugin output if defined, must be an object with a valid semver version in the "version" property and the corresponding git reference in "gitHead" property. Received: { version: '1.8.0' }
    at Object.getLastRelease (/home/travis/build/buehler/typescript-hero/node_modules/semantic-release/lib/plugins/normalize.js:44:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

That's the output of SR when I run it with version 12.

Is there something missing?

(package.json):
```json
"release": {
    "verifyConditions": [
      "semantic-release-vsce",
      "@semantic-release/github"
    ],
    "getLastRelease": "semantic-release-vsce",
    "publish": [
      {
        "path": "semantic-release-vsce",
        "packageVsix": "your-extension.vsix"
      },
      {
        "path": "@semantic-release/github",
        "assets": "your-extension.vsix"
      }
    ]
  },
````
Cheers

**Comment by buehler** [comment]
For now, I cloned your file and added some custom scripts, I'll open a pull request with the changes that I made.

**Comment by raix** [comment]
Yeah, maybe I should just revert the upgrade commit - the semver guys broke this by making the vsce release resposible of providing a `gitHead` *(but we might be using github/gitlab or some other plugins)*

ref: https://github.com/semantic-release/semantic-release/issues/607

**Comment by felixfbecker** [comment]
To be fair, the `peerDependency` in package.json clearly states that this plugin is compatible with semantic-release ^11.0.0, not 12.0.0
