### ISSUE TITLE
Error using @semantic-release/git on the getLastRelease hook

### ISSUE THREAD

**Issue by GabeDuarteM** [felipecrs/semantic-release-vsce#16]
As of `@semantic-release/git v3.0.0` (https://github.com/semantic-release/git/commit/c8119dacd845f9c84667186bab1ef160f519a75b), `getLastRelease` is no longer part of the `@semantic-release/git` plugin, so you if configure `semantic-release-vsce` as it is said in the readme, using `"getLastRelease": "@semantic-release/git"`, semantic-release throws the following error: `EPLUGINCONF The getLastRelease plugin must be a function, or an object with a function in the property getLastRelease.`

Is there any way to continue using this plugin without having to downgrade `@semantic-release/git` to `v2.2.0`?

**Comment by kumarharsh** [comment]
It works well with `@semantic-release/git` - `getLastRelease` is not needed as it got pulled into the [core plugin](https://github.com/semantic-release/semantic-release/commit/d0b304e240002ed22f1d30b866260f6582518938#diff-092b51f327b91c27b8aa63a459aa8a84).

**Comment by raix** [comment]
@GabrielDuarteM do we need to update the readme in this project?

**Comment by GabeDuarteM** [comment]
@raix I don't think so, as we now have a [Working with older versions](https://github.com/raix/semantic-release-vsce#working-with-older-versions) section already on the readme, which I think clarifies that 👍
