### ISSUE TITLE
The Personal Access Token verification has failed

### ISSUE THREAD

**Issue by gleisonkz** [felipecrs/semantic-release-vsce#279]
Hi, I'm trying to use this plugin to release a sample vscode extension, but I'm getting this error about the vsce access token

any clue on what am I doing wrong?

![image](https://user-images.githubusercontent.com/48810597/167901536-e1b72af6-71ec-47e9-b485-62e81bc7913c.png)

Link Repository:
https://github.com/ngx-devs/ngxd-console-test

Action:
https://github.com/ngx-devs/ngxd-console-test/runs/6392104433?check_suite_focus=true

**Comment by felipecrs** [comment]
I suppose you configured the `VSCE_PAT` as a secret in your repository configuration, right?

If so, can you try to run the command in your local environment to see if the same issue happens:

```console
$  export VSCE_PAT=<your-pat>
$ npx vsce verify-pat
```

**Comment by gleisonkz** [comment]
I tried this, but unfortunately, I'm having the same problem, it might be something with the generate access token?

![image](https://user-images.githubusercontent.com/48810597/167954794-37763e9c-9890-49c9-bb6f-deb16a2d0e30.png)

**Comment by felipecrs** [comment]
Yes, your personal access token most likely lacks permission to publish in the given VS Marketplace publisher.

I suggest you to follow up in https://github.com/microsoft/vscode-vsce in case you need more help.

**Comment by felipecrs** [comment]
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

**Comment by gleisonkz** [comment]
@felipecrs  thanks for your help, the problem was that I was not setting the "All accessible organizations" option in Organization select box.

**Comment by felipecrs** [comment]
Glad it worked, thanks for reporting back! :D

**Comment by felixjb** [comment]
Hello @felipecrs ! I have the same problem, but in my case, the token is correct and is correctly saved and referenced in my action secrets.

`vsce verify-pat` result:

```
The Personal Access Token verification succeeded for the publisher 'felixjb'.
```

What can I do in this case?

**Comment by felixjb** [comment]
Also, here's the repo, in case any configuration need close examination: https://github.com/felixjb/testify
