### ISSUE TITLE
Check that access token is still valid in verify step

### ISSUE THREAD

**Issue by jedwards1211** [felipecrs/semantic-release-vsce#308]
I had a publish fail because my personal access token was expired.  However, the `verifyConditions` step of `semantic-release-vsce` passed so `semantic-release` ended up creating and pushing the git tag, meaning on the next CI build it mistakenly thought various commits had been published, when they hadn't. 

The `npm` plugin verifies the `npm` token in the `verifyConditions` step in most cases: https://github.com/semantic-release/npm/blob/master/index.js#L36

**Comment by felipecrs** [comment]
This already happens. Can you tell what `cd <your-project> && VSCE_PAT=<token> npx vsce verify-pat` says?

https://github.com/felipecrs/semantic-release-vsce/blob/e41be8ca6b87779f41dc1f3f99c09268e82b6097/lib/verify-auth.js#L12

**Comment by felipecrs** [comment]
i.e., if it passes for your expired token, open an issue against https://github.com/microsoft/vscode-vsce instead.

**Comment by jedwards1211** [comment]
Oh looks like I'm on a very old version of `semantic-release-vsce` though (2.2.8).  Any idea if this was fixed since then?  Unfortunately, I no longer have that expired token...

**Comment by felipecrs** [comment]
Yeah, this was introduced in v3.2.0.

https://github.com/felipecrs/semantic-release-vsce/releases/tag/v3.2.0

As it should be working and you can't reproduce it any longer, I will close the issue.

**Comment by jedwards1211** [comment]
thanks, sorry for the interruption!

**Comment by felipecrs** [comment]
> thanks, sorry for the interruption!

No worries, you are welcome!
