### ISSUE TITLE
Setting package root

### ISSUE THREAD

**Issue by OmarTawfik** [felipecrs/semantic-release-vsce#32]
Hi,

I've a github project that is pushing multiple packages (npm, vsce, etc...)
Each are built to an `out` folder with custom `package.json`

For npm, I define the path as:
```json
    [
      "@semantic-release/npm",
      {
        "pkgRoot": "./out/linter"
      }
    ],
```

But I cannot find a similar setting for vsce, which result in the plugin publishing the root sources instead of `out/vscode`, which basically publishes an unusable package.

I wonder how can that be done using this plugin?

**Comment by raix** [comment]
Hi @OmarTawfik good point - we currently don't set `cwd` in `execa` and some paths - but I don't see any reason why not to.

I'm not sure how settings are passed on to this plugin maybe @felixfbecker knows?

---

https://github.com/raix/semantic-release-vsce/blob/master/lib/prepare.js#L9
https://github.com/raix/semantic-release-vsce/blob/master/lib/publish.js#L10
https://github.com/raix/semantic-release-vsce/blob/master/lib/update-package-version.js#L9

**Comment by felixfbecker** [comment]
Idk, settings are passed the same way as for any other plugin

**Comment by OmarTawfik** [comment]
Maybe through `pluginConfig` in https://github.com/raix/semantic-release-vsce/blob/master/index.js?
TBH, I don't know much about testing semantic release extensions (I just started using it today) 😄

**Comment by felipecrs** [comment]
Just to update, this isn't rejected. There was a PR which just lacked finalization: https://github.com/felipecrs/semantic-release-vsce/issues/32

It will arrive, someday.
