### ISSUE TITLE
Support additional params to package and publish

### ISSUE THREAD

**Issue by unional** [felipecrs/semantic-release-vsce#442]
Hi, I'm using `pnpm` and there is a workaround needed: https://github.com/microsoft/vscode-vsce/issues/421#issuecomment-1038911725

```json5
// this is my package.json
"scripts": {
    "package": "pnpm vsce package --no-dependencies",
    "publish": "pnpm vsce publish --no-dependencies"
}
```

Without it, the release fails with:

```sh
Error: Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! code ELSPROBLEMS
```

**Comment by felipecrs** [comment]
Hey, you can set vsce options in the package.json through the vsce key. Check the vsce docs.

Try that, and let me know if it doesn't work.

**Comment by unional** [comment]
Hi, I went through the doc here:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

But I can't seem to find the vsce options you are talking about.

I have tried things like:

```json5
{
  "scripts": {
    "publish": "pnpm vsce publish --no-dependencies"
  }
}
```

But that doesn't seem to pick up by `semantic-release-vsce`.

Can you share which options you are referring to?

**Comment by felipecrs** [comment]
This one:

https://github.com/microsoft/vscode-vsce#configuration

**Comment by unional** [comment]
awesome 🍻 thx!

**Comment by felipecrs** [comment]
- Hopefully https://github.com/felipecrs/semantic-release-vsce/pull/443 will make it simpler for others to follow.
