### ISSUE TITLE
Optionally support deploying to OpenVSX

### ISSUE THREAD

**Issue by felipecrs** [felipecrs/semantic-release-vsce#62]
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by GitMensch** [comment]
Can the message of the bot include the related Open-VSX page in the "the release is available on" message (issue update) shown below and the "this release is also available on" (GH release), too?

**Comment by felipecrs** [comment]
@GitMensch unfortunately, it's not currently possible: semantic-release/semantic-release#2123

Unless I decouple the `ovsx` from the `semantic-release-vsce`, and create a `semantic-release-ovsx`.

**Comment by felipecrs** [comment]
It was part of the original implementation until I realized that it didn't work.

https://github.com/felipecrs/semantic-release-vsce/blob/5b40b1b55780bfb98bce39931bc7141ba6274a81/lib/publish.js#L39-L43

**Comment by GitMensch** [comment]
Please try to don't decouple - one version is better and two entries in the issue messages and releases would be bad, too [maybe a potential second CI could edit the work of the former, but that seems to be a strange design]. For now: whichever release was done first should get the entry (in case only open-vsx is used); more discussion on this can go on in semantic-release/semantic-release#2123.

... thinking of this, maybe it is a good time already to rename this repo (or package.json entries) to something like "semantic-release-vsix-publish", just an idea so far...

Not sure, but do you already use osvx to publish to both marketplaces when it is configured? This may/may not help with the multiple return paths a bit.
