### ISSUE TITLE
Will this project going to be maintained?

### ISSUE THREAD

**Issue by felipecrs** [felipecrs/semantic-release-vsce#64]
I'm about to create a fork of it because I need to add more features to this plugin to use it. 

However, it's always good to prevent unneeded forks so people do not get confused.

If you're looking for maintainers, I'm also willing to help.

/cc @raix @felixfbecker

**Comment by raix** [comment]
@felipecrs sorry for the late reply - I'm personally low on time atm. If you are still up for it I can add you to the project, would be great with help :)

**Comment by raix** [comment]
@felipecrs I've sent an invite

**Comment by felipecrs** [comment]
Amazing, thank you very much! I'll port-back the changes I made in my fork.

**Comment by raix** [comment]
@felipecrs I could transfer the project to you if you want? (would need to figure out how to do in on npm but it should be doable)

**Comment by felipecrs** [comment]
@raix if you are okay with it, I'm ok.

And it's quite simple to transfer it on npm as well: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

My npm profile: https://www.npmjs.com/~felipecrs

**Comment by raix** [comment]
@felipecrs sorry about the late response, I'll transfer the package to you - if ok with you?

**Comment by raix** [comment]
@felipecrs I've added you as maintainer on npm - I tried to transfer this repo but it already exists on your username in github.

**Comment by felipecrs** [comment]
> if ok with you?

Yeap!

> I've added you as maintainer on npm

Thank you! I just confirmed here.

> I tried to transfer this repo but it already exists on your username in github.

I just renamed my fork, it should work now.

**Comment by raix** [comment]
@felipecrs I've set github to transfer - I'll transfer npm ownership to you later this weekend. Btw. enable 2fa on npm

Thank you :)

**Comment by felipecrs** [comment]
I just enabled. Thanks for reminding! I also accepted the ownership transfer on GitHub.

Thanks so much! I'll keep you as maintainer in the repo.

**Comment by raix** [comment]
@felipecrs I've followed the guide to transfer ownership - part of the guide was to remove myself as maintainer on the package in npm - when trying to add you as the owner I got an error - I've written to npm support to help out fixing the issue.

```
npm owner add felipecrs semantic-release-vsce
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/semantic-release-vsce/-rev/20-4e48776---86c19e - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

**Comment by raix** [comment]
@felixfbecker maybe you can try running `npm owner add felipecrs semantic-release-vsce` ?

**Comment by felipecrs** [comment]
@raix In the last time I did this, I contacted the NPM support and they did it right away. 

They should probably answer soon. Let's see.

**Comment by felipecrs** [comment]
I think this is now fixed:

```sh-session
❯ npm owner ls semantic-release-vsce --otp 100982
felixfbecker <x>
felipecrs <x>
```

Thanks so much, @felixfbecker and @raix!

**Comment by raix** [comment]
@felipecrs yep looks correct now :)

Thank you

Kind regards Morten
