### ISSUE TITLE
Add support for VSCE authentication via the `--azure-credential` flag

### ISSUE THREAD

**Issue by JakeShirley** [felipecrs/semantic-release-vsce#662]
Hard to find in the documentation, but the flag can be found here: https://github.com/microsoft/vscode-vsce/blob/cf0bc3242b9adac3b25c9d7ea0de78842203d123/src/main.ts#L191

I might take a swing at doing this at some point as Microsoft leans away from PATs.

**Comment by felipecrs** [comment]
Makes sense. Please feel free to contribute this by reading the value from an environment variable.

**Comment by felipecrs** [comment]
Closed by #663
